name: build-bundle
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - constructor >=3.11.0
  - conda-build >=3.28
  - ruamel.yaml
  - conda-standalone >=24.7.1
  - conda >=24.7.1
  - conda-libmamba-solver
  - libmamba >=2,<2.3
  # only needed to import napari and get the path to the logo.png file
  - lazy_loader >=0.2
  - numpy >=1.22.2
